<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net8.0-windows</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UseWPF>true</UseWPF>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="MaterialDesignThemes" Version="5.2.2-ci942" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Assets\Icon\" />
    </ItemGroup>

    <ItemGroup>
      <None Remove="Assets\Icon\logo.ico" />
      <Resource Include="Assets\Icon\logo.ico" />
      <None Remove="Assets\Images\calc.png" />
      <None Remove="Assets\Images\notepad.png" />
      <None Remove="Assets\Images\paint.png" />
      <None Remove="Assets\Images\setings.png" />
    </ItemGroup>

</Project>
